# Generated by Django 3.2.6 on 2021-10-31 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_name', models.CharField(max_length=100)),
                ('Recipe_description', models.TextField()),
                ('Recipe_type', models.CharField(max_length=100)),
                ('Recipe_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_prep_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time', models.DurationField()),
                ('num_of_servings', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('Recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Nutri_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_per_serving', models.CharField(max_length=100)),
                ('carbs', models.CharField(max_length=100)),
                ('proteins', models.CharField(max_length=100)),
                ('saturated_fat', models.CharField(max_length=100)),
                ('trans_fat', models.CharField(max_length=100)),
                ('cholestrol', models.CharField(max_length=100)),
                ('Recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
